title: Naowal Siripatana # your name (or website title) here
logo: "https://raw.githubusercontent.com/naowal/naowal.github.io/master/images/0.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software engineer with 5 years of experience coding and analysing digital products. Good at self-management with remote work environment. Determined and focused on back-end and API development. Proactive team player with an inquisitive mind. Committed to grow experience in the field of design and programming development. 
  <br><br>
  Looking for remote work with welfare. Django , Python Programing , QA Testing and Data engineering.
  <br><br>
  <a href="https://www.linkedin.com/in/naowal-siripatana-b8b252ba/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minima
google_analytics: UA-151814771-1 # your Google Analytics tracking ID here
