title: Naowal Siripatana # your name (or website title) here
logo: "https://raw.githubusercontent.com/naowal/naowal.github.io/master/images/0.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Full Stack Engineer with easy-going, honestly and pursuit of excellence, Joined the Computer Academic Olympics Camp when in high school which will get tuition fee scholarship to study in the university. Her opinion is being hired as remotely work.
  <br><br>
  Looking for remote work with welfare. Django , Python Programing , QA Testing and Data engineering.
  <br><br>
  <a href="https://www.linkedin.com/in/naowal-siripatana-b8b252ba/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-architect
google_analytics: UA-151814771-1 # your Google Analytics tracking ID here
